- name: Ping host
  ansible.builtin.ping:

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages for this project
  ansible.builtin.apt:
    name:
      - atop
      - build-essential 
      - cmake 
      - docker
      - docker-compose
      - git
      - gnutls-bin
      - gpsd
      - htop
      - i2c-tools
      - libffi-dev
      - libqmi-utils
      - libssl-dev
      - libudev-dev
      - libusb-1.0-0-dev 
      - minicom
      - mlocate
      - mtr
      - p7zip-full
      - python3 
      - python3-pip
      - socat
      - udhcpc
      - vim
    state: present

- name: apt upgrade
  ansible.builtin.apt:
    upgrade: yes
    
- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: apt clean
  apt:
    clean: yes

- name: Stop docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: yes
  loop: 
    - docker.service 
    - docker.socket

- name: Add docker group to user pi
  ansible.builtin.user:
    name: pi
    shell: /bin/bash
    groups: docker,gpio,i2c,spi
    append: yes

- name: Start and Enable docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: 
    - docker.service 
    - docker.socket