version: "3.6"
networks:
  loranet:
    external: true
services:
  rabbitmq:
    image: rabbitmq:3.10.6-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /edgeserver/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /edgeserver/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - /edgeserver/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - /edgeserver/rabbitmq/data:/var/lib/rabbitmq
      - /edgeserver/rabbitmq/logs:/var/log/rabbitmq
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
    networks:
      loranet:
        # ipv4_address: 172.19.0.3