version: "3.3"
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.10.6-management
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    ports:
      - "8883:1883"
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./data:/var/lib/rabbitmq
      - ./logs:/var/log/rabbitmq
