version: '3.6'
networks:
  loranet:
    external: true
services:
  udp-packet-forwarder:
    image: rakwireless/udp-packet-forwarder:v1.1.3
    container_name: udpforwarder
    hostname: udpforwarder
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    privileged: true
    # network_mode: host
    environment:
      MODEL: "RAK7371"
      MODULE: "RAK5146"
      CONCENTRATOR: "SX1303"
      HAS_GPS: "0"
      INTERFACE: "USB"
      GATEWAY_EUI: "26E804FFFE7093C0"
      SERVER_HOST: "gatewaybridge"
      SERVER_PORT: "1700"
      RADIO_DEV: "/dev/ttyACM0"
      GATEWAY_EUI_NIC: "usb0"
      BAND: "us_902_928"
      GPS_LATITUDE: "35.995951"
      GPS_LONGITUDE: "-115.126651"
    networks:
      loranet:
        # ipv4_address: 172.19.0.6