version: "3.6"
networks:
  loranet:
    external: true
services:
  vault:
    image: vault:1.9.2
    container_name: vault
    hostname: vault
    restart: always
    volumes:
      - /edgeserver/vault/data:/edgeserver/vault/data/
      - /edgeserver/vault/etc/config.hcl:/etc/vault/config.hcl
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/etc/vault/config.hcl
    ports:
      - "8200:8200"
    networks:
      loranet:
        # ipv4_address: 172.19.0.2
