version: "3.6"
networks:
  loranet:
    external: true
services:
  vault:
    image: vault:1.9.2
    container_name: vault
    hostname: vault
    restart: always
    volumes:
      - /edgeserver/vault/data:/edgeserver/vault/data/
      - /edgeserver/vault/etc/config.hcl:/etc/vault/config.hcl
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/etc/vault/config.hcl
    ports:
      - "8200:8200"
    networks:
      loranet:
        # ipv4_address: 172.19.0.2

  rabbitmq:
    image: rabbitmq:3.10.6-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /edgeserver/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /edgeserver/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - /edgeserver/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - /edgeserver/rabbitmq/data:/var/lib/rabbitmq
      - /edgeserver/rabbitmq/logs:/var/log/rabbitmq
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
    networks:
      loranet:
        # ipv4_address: 172.19.0.3

  influxdb:
    image: influxdb:2.1.1-alpine
    container_name: influxdb
    hostname: influxdb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /edgeserver/influxdb/config.yml:/etc/influxdb2/config.yml
      - /edgeserver/influxdb:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    networks:
      loranet:
        # ipv4_address: 172.19.0.4

  gatewaybridge:
    image: chirpstack/chirpstack-gateway-bridge:3.14.0
    container_name: gatewaybridge
    hostname: gatewaybridge
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - rabbitmq
    ports:
      - "1700:1700/udp"
    volumes:
      - /edgeserver/gatewaybridge/chirpstack-gateway-bridge.toml:/etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml
      - /edgeserver/gatewaybridge/data:/var/lib/gw_bridge
      - /edgeserver/gatewaybridge/logs:/var/log/gw_bridge
    networks:
      loranet:
        # ipv4_address: 172.19.0.5

  udp-packet-forwarder:
    image: rakwireless/udp-packet-forwarder:v1.1.3
    container_name: udpforwarder
    hostname: udpforwarder
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - gatewaybridge
    privileged: true
      #network_mode: host
    environment:
      MODEL: "RAK7371"
      MODULE: "RAK5146"
      CONCENTRATOR: "SX1303"
      HAS_GPS: "0"
      INTERFACE: "USB"
      GATEWAY_EUI: "26E804FFFE7093C0"
      SERVER_HOST: "gatewaybridge"
      SERVER_PORT: "1700"
      RADIO_DEV: "/dev/ttyACM0"
      GATEWAY_EUI_NIC: "usb0"
      BAND: "us_902_928"
      GPS_LATITUDE: "35.995951"
      GPS_LONGITUDE: "-115.126651"
    networks:
      loranet:
        # ipv4_address: 172.19.0.6

  nodered:
    image: nodered/node-red:2.2.2-12
    container_name: nodered
    hostname: nodered
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /edgeserver/nodered/data:/data:rw
    environment:
      - TZ=America/Los_Angeles
    ports:
      - "1880:1880"
    networks:
      loranet:
        # ipv4_address: 172.19.0.7
