---
- name: Setting up Edgeserver
  hosts: all
  gather_facts: false
  vars:
    ansible_user: pi
    ansible_ssh_private_key_file: ~/.ssh/pi
  tasks:
    - name: Ping host
      ansible.builtin.ping:

    # - name: Update apt cache
    #   ansible.builtin.apt:
    #     update_cache: yes
    #   become: true
    #   become_method: sudo

    # - name: Remove useless packages from the cache
    #   ansible.builtin.apt:
    #     autoclean: yes
    #   become: true
    #   become_method: sudo

    # - name: Remove dependencies that are no longer required
    #   ansible.builtin.apt:
    #     autoremove: yes
    #   become: true
    #   become_method: sudo

    # - name: Run the equivalent of "apt-get clean" as a separate step
    #   apt:
    #     clean: yes
    #   become: true
    #   become_method: sudo

    - name: Pull alpine image
      community.docker.docker_image:
        name: alpine
        source: pull
        pull:
          platform: arm64
