---
- name: edgeserver setup
  hosts: all
  gather_facts: false
  vars:
    ansible_user: pi
    ansible_ssh_private_key_file: ~/.ssh/pi_key
  roles:
    - firstboot
    - base
    - apps
    - chirpstack
  become: true
  become_method: sudo
  environment: 
    DEBIAN_FRONTEND: noninteractive
