version: '3.6'
networks:
  loranet:
    external: true
services:
  nodered:
    container_name: nodered
    hostname: nodered
    restart: always
    image: nodered/node-red:2.2.2-12
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /edgeserver/nodered/data:/data:rw
    networks:
      loranet:
    ports:
      - "1880:1880"
    environment:
      - TZ=America/Los_Angeles
